Simulation
clubcapra/rove pull request #4
Opened 2023-12-08 17:12 UTC by SimonR99

- add simulation in dev container (windows support)
- add simulation file for rove (urdf)
- add default world

2023-12-10 21:55 UTC, Leuchak commented on src/rove_description/package.xml
> +  <maintainer email="capra@etsmtl.ca">user</maintainer>
capra@ens.etsmtl.ca

2023-12-10 22:13 UTC, Leuchak requested changes
How do I test this ?

2023-12-10 22:19 UTC, SimonR99 commented
I'll add a readme before merging. To this it meanwhile :

colcon build --symlink-install
source install/setup.bash
ros2 launch rove_description sim.launch.py

2023-12-11 17:36 UTC, Leuchak approved these changes
let's go

2023-12-11 17:36 UTC, merged